// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameConstants.proto

package com.orange.network.game.protocol.constants;

public final class GameConstantsProtos {
  private GameConstantsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum GameCommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    JOIN_GAME_REQUEST(0, 1),
    JOIN_GAME_RESPONSE(1, 2),
    START_GAME_REQUEST(2, 3),
    START_GAME_RESPONSE(3, 4),
    QUIT_GAME_REQUEST(4, 5),
    QUIT_GAME_RESPONSE(5, 6),
    SEND_DRAW_DATA_REQUEST(6, 11),
    SEND_DRAW_DATA_RESPONSE(7, 12),
    CLEAN_DRAW_REQUEST(8, 13),
    CLEAN_DRAW_RESPONSE(9, 14),
    PROLONG_GAME_REQUEST(10, 15),
    PROLONG_GAME_RESPONSE(11, 16),
    COMPLETE_GAME_REQUEST(12, 17),
    COMPLETE_GAME_RESPONSE(13, 18),
    USER_JOIN_NOTIFICATION_REQUEST(14, 51),
    USER_JOIN_NOTIFICATION_RESPONSE(15, 52),
    USER_QUIT_NOTIFICATION_REQUEST(16, 53),
    USER_QUIT_NOTIFICATION_RESPONSE(17, 54),
    HOST_CHANGE_NOTIFICATION_REQUEST(18, 61),
    HOST_CHANGE_NOTIFICATION_RESPONSE(19, 62),
    GAME_START_NOTIFICATION_REQUEST(20, 55),
    GAME_START_NOTIFICATION_RESPONSE(21, 56),
    NEW_DRAW_DATA_NOTIFICATION_REQUEST(22, 71),
    NEW_DRAW_DATA_NOTIFICATION_RESPONSE(23, 72),
    CLEAN_DRAW_NOTIFICATION_REQUEST(24, 73),
    CLEAN_DRAW_NOTIFICATION_RESPONSE(25, 74),
    PROLONG_GAME_NOTIFICATION_REQUEST(26, 75),
    PROLONG_GAME_NOTIFICATION_RESPONSE(27, 76),
    GAME_TURN_COMPLETE_NOTIFICATION_REQUEST(28, 77),
    GAME_TURN_COMPLETE_NOTIFICATION_RESPONSE(29, 78),
    LOCAL_CHANNEL_DISCONNECT(30, 201),
    LOCAL_FINISH_GAME(31, 203),
    LOCAL_JOIN_GAME(32, 204),
    LOCAL_GAME_TURN_COMPLETE(33, 205),
    ;
    
    public static final int JOIN_GAME_REQUEST_VALUE = 1;
    public static final int JOIN_GAME_RESPONSE_VALUE = 2;
    public static final int START_GAME_REQUEST_VALUE = 3;
    public static final int START_GAME_RESPONSE_VALUE = 4;
    public static final int QUIT_GAME_REQUEST_VALUE = 5;
    public static final int QUIT_GAME_RESPONSE_VALUE = 6;
    public static final int SEND_DRAW_DATA_REQUEST_VALUE = 11;
    public static final int SEND_DRAW_DATA_RESPONSE_VALUE = 12;
    public static final int CLEAN_DRAW_REQUEST_VALUE = 13;
    public static final int CLEAN_DRAW_RESPONSE_VALUE = 14;
    public static final int PROLONG_GAME_REQUEST_VALUE = 15;
    public static final int PROLONG_GAME_RESPONSE_VALUE = 16;
    public static final int COMPLETE_GAME_REQUEST_VALUE = 17;
    public static final int COMPLETE_GAME_RESPONSE_VALUE = 18;
    public static final int USER_JOIN_NOTIFICATION_REQUEST_VALUE = 51;
    public static final int USER_JOIN_NOTIFICATION_RESPONSE_VALUE = 52;
    public static final int USER_QUIT_NOTIFICATION_REQUEST_VALUE = 53;
    public static final int USER_QUIT_NOTIFICATION_RESPONSE_VALUE = 54;
    public static final int HOST_CHANGE_NOTIFICATION_REQUEST_VALUE = 61;
    public static final int HOST_CHANGE_NOTIFICATION_RESPONSE_VALUE = 62;
    public static final int GAME_START_NOTIFICATION_REQUEST_VALUE = 55;
    public static final int GAME_START_NOTIFICATION_RESPONSE_VALUE = 56;
    public static final int NEW_DRAW_DATA_NOTIFICATION_REQUEST_VALUE = 71;
    public static final int NEW_DRAW_DATA_NOTIFICATION_RESPONSE_VALUE = 72;
    public static final int CLEAN_DRAW_NOTIFICATION_REQUEST_VALUE = 73;
    public static final int CLEAN_DRAW_NOTIFICATION_RESPONSE_VALUE = 74;
    public static final int PROLONG_GAME_NOTIFICATION_REQUEST_VALUE = 75;
    public static final int PROLONG_GAME_NOTIFICATION_RESPONSE_VALUE = 76;
    public static final int GAME_TURN_COMPLETE_NOTIFICATION_REQUEST_VALUE = 77;
    public static final int GAME_TURN_COMPLETE_NOTIFICATION_RESPONSE_VALUE = 78;
    public static final int LOCAL_CHANNEL_DISCONNECT_VALUE = 201;
    public static final int LOCAL_FINISH_GAME_VALUE = 203;
    public static final int LOCAL_JOIN_GAME_VALUE = 204;
    public static final int LOCAL_GAME_TURN_COMPLETE_VALUE = 205;
    
    
    public final int getNumber() { return value; }
    
    public static GameCommandType valueOf(int value) {
      switch (value) {
        case 1: return JOIN_GAME_REQUEST;
        case 2: return JOIN_GAME_RESPONSE;
        case 3: return START_GAME_REQUEST;
        case 4: return START_GAME_RESPONSE;
        case 5: return QUIT_GAME_REQUEST;
        case 6: return QUIT_GAME_RESPONSE;
        case 11: return SEND_DRAW_DATA_REQUEST;
        case 12: return SEND_DRAW_DATA_RESPONSE;
        case 13: return CLEAN_DRAW_REQUEST;
        case 14: return CLEAN_DRAW_RESPONSE;
        case 15: return PROLONG_GAME_REQUEST;
        case 16: return PROLONG_GAME_RESPONSE;
        case 17: return COMPLETE_GAME_REQUEST;
        case 18: return COMPLETE_GAME_RESPONSE;
        case 51: return USER_JOIN_NOTIFICATION_REQUEST;
        case 52: return USER_JOIN_NOTIFICATION_RESPONSE;
        case 53: return USER_QUIT_NOTIFICATION_REQUEST;
        case 54: return USER_QUIT_NOTIFICATION_RESPONSE;
        case 61: return HOST_CHANGE_NOTIFICATION_REQUEST;
        case 62: return HOST_CHANGE_NOTIFICATION_RESPONSE;
        case 55: return GAME_START_NOTIFICATION_REQUEST;
        case 56: return GAME_START_NOTIFICATION_RESPONSE;
        case 71: return NEW_DRAW_DATA_NOTIFICATION_REQUEST;
        case 72: return NEW_DRAW_DATA_NOTIFICATION_RESPONSE;
        case 73: return CLEAN_DRAW_NOTIFICATION_REQUEST;
        case 74: return CLEAN_DRAW_NOTIFICATION_RESPONSE;
        case 75: return PROLONG_GAME_NOTIFICATION_REQUEST;
        case 76: return PROLONG_GAME_NOTIFICATION_RESPONSE;
        case 77: return GAME_TURN_COMPLETE_NOTIFICATION_REQUEST;
        case 78: return GAME_TURN_COMPLETE_NOTIFICATION_RESPONSE;
        case 201: return LOCAL_CHANNEL_DISCONNECT;
        case 203: return LOCAL_FINISH_GAME;
        case 204: return LOCAL_JOIN_GAME;
        case 205: return LOCAL_GAME_TURN_COMPLETE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<GameCommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameCommandType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameCommandType>() {
            public GameCommandType findValueByNumber(int number) {
              return GameCommandType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.orange.network.game.protocol.constants.GameConstantsProtos.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final GameCommandType[] VALUES = {
      JOIN_GAME_REQUEST, JOIN_GAME_RESPONSE, START_GAME_REQUEST, START_GAME_RESPONSE, QUIT_GAME_REQUEST, QUIT_GAME_RESPONSE, SEND_DRAW_DATA_REQUEST, SEND_DRAW_DATA_RESPONSE, CLEAN_DRAW_REQUEST, CLEAN_DRAW_RESPONSE, PROLONG_GAME_REQUEST, PROLONG_GAME_RESPONSE, COMPLETE_GAME_REQUEST, COMPLETE_GAME_RESPONSE, USER_JOIN_NOTIFICATION_REQUEST, USER_JOIN_NOTIFICATION_RESPONSE, USER_QUIT_NOTIFICATION_REQUEST, USER_QUIT_NOTIFICATION_RESPONSE, HOST_CHANGE_NOTIFICATION_REQUEST, HOST_CHANGE_NOTIFICATION_RESPONSE, GAME_START_NOTIFICATION_REQUEST, GAME_START_NOTIFICATION_RESPONSE, NEW_DRAW_DATA_NOTIFICATION_REQUEST, NEW_DRAW_DATA_NOTIFICATION_RESPONSE, CLEAN_DRAW_NOTIFICATION_REQUEST, CLEAN_DRAW_NOTIFICATION_RESPONSE, PROLONG_GAME_NOTIFICATION_REQUEST, PROLONG_GAME_NOTIFICATION_RESPONSE, GAME_TURN_COMPLETE_NOTIFICATION_REQUEST, GAME_TURN_COMPLETE_NOTIFICATION_RESPONSE, LOCAL_CHANNEL_DISCONNECT, LOCAL_FINISH_GAME, LOCAL_JOIN_GAME, LOCAL_GAME_TURN_COMPLETE, 
    };
    
    public static GameCommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private GameCommandType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:game.GameCommandType)
  }
  
  public enum GameResultCode
      implements com.google.protobuf.ProtocolMessageEnum {
    SUCCESS(0, 0),
    ERROR_JOIN_GAME(1, 1),
    ERROR_USERID_NULL(2, 100),
    ERROR_USER_CANNOT_START_GAME(3, 101),
    ERROR_NO_SESSION_ID(4, 200),
    ERROR_NEXT_STATE_NOT_FOUND(5, 201),
    ERROR_SESSIONID_NULL(6, 202),
    ERROR_SESSION_ALREADY_START(7, 203),
    ERROR_SESSION_NOT_START(8, 204),
    ERROR_NO_SESSION_AVAILABLE(9, 205),
    ERROR_NO_DRAW_DATA(10, 301),
    ERROR_SYSTEM_HANDLER_NOT_FOUND(11, 910),
    ERROR_SYSTEM_EXCEPTION(12, 911),
    ;
    
    public static final int SUCCESS_VALUE = 0;
    public static final int ERROR_JOIN_GAME_VALUE = 1;
    public static final int ERROR_USERID_NULL_VALUE = 100;
    public static final int ERROR_USER_CANNOT_START_GAME_VALUE = 101;
    public static final int ERROR_NO_SESSION_ID_VALUE = 200;
    public static final int ERROR_NEXT_STATE_NOT_FOUND_VALUE = 201;
    public static final int ERROR_SESSIONID_NULL_VALUE = 202;
    public static final int ERROR_SESSION_ALREADY_START_VALUE = 203;
    public static final int ERROR_SESSION_NOT_START_VALUE = 204;
    public static final int ERROR_NO_SESSION_AVAILABLE_VALUE = 205;
    public static final int ERROR_NO_DRAW_DATA_VALUE = 301;
    public static final int ERROR_SYSTEM_HANDLER_NOT_FOUND_VALUE = 910;
    public static final int ERROR_SYSTEM_EXCEPTION_VALUE = 911;
    
    
    public final int getNumber() { return value; }
    
    public static GameResultCode valueOf(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return ERROR_JOIN_GAME;
        case 100: return ERROR_USERID_NULL;
        case 101: return ERROR_USER_CANNOT_START_GAME;
        case 200: return ERROR_NO_SESSION_ID;
        case 201: return ERROR_NEXT_STATE_NOT_FOUND;
        case 202: return ERROR_SESSIONID_NULL;
        case 203: return ERROR_SESSION_ALREADY_START;
        case 204: return ERROR_SESSION_NOT_START;
        case 205: return ERROR_NO_SESSION_AVAILABLE;
        case 301: return ERROR_NO_DRAW_DATA;
        case 910: return ERROR_SYSTEM_HANDLER_NOT_FOUND;
        case 911: return ERROR_SYSTEM_EXCEPTION;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<GameResultCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameResultCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameResultCode>() {
            public GameResultCode findValueByNumber(int number) {
              return GameResultCode.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.orange.network.game.protocol.constants.GameConstantsProtos.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final GameResultCode[] VALUES = {
      SUCCESS, ERROR_JOIN_GAME, ERROR_USERID_NULL, ERROR_USER_CANNOT_START_GAME, ERROR_NO_SESSION_ID, ERROR_NEXT_STATE_NOT_FOUND, ERROR_SESSIONID_NULL, ERROR_SESSION_ALREADY_START, ERROR_SESSION_NOT_START, ERROR_NO_SESSION_AVAILABLE, ERROR_NO_DRAW_DATA, ERROR_SYSTEM_HANDLER_NOT_FOUND, ERROR_SYSTEM_EXCEPTION, 
    };
    
    public static GameResultCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private GameResultCode(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:game.GameResultCode)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023GameConstants.proto\022\004game*\322\010\n\017GameComm" +
      "andType\022\025\n\021JOIN_GAME_REQUEST\020\001\022\026\n\022JOIN_G" +
      "AME_RESPONSE\020\002\022\026\n\022START_GAME_REQUEST\020\003\022\027" +
      "\n\023START_GAME_RESPONSE\020\004\022\025\n\021QUIT_GAME_REQ" +
      "UEST\020\005\022\026\n\022QUIT_GAME_RESPONSE\020\006\022\032\n\026SEND_D" +
      "RAW_DATA_REQUEST\020\013\022\033\n\027SEND_DRAW_DATA_RES" +
      "PONSE\020\014\022\026\n\022CLEAN_DRAW_REQUEST\020\r\022\027\n\023CLEAN" +
      "_DRAW_RESPONSE\020\016\022\030\n\024PROLONG_GAME_REQUEST" +
      "\020\017\022\031\n\025PROLONG_GAME_RESPONSE\020\020\022\031\n\025COMPLET" +
      "E_GAME_REQUEST\020\021\022\032\n\026COMPLETE_GAME_RESPON",
      "SE\020\022\022\"\n\036USER_JOIN_NOTIFICATION_REQUEST\0203" +
      "\022#\n\037USER_JOIN_NOTIFICATION_RESPONSE\0204\022\"\n" +
      "\036USER_QUIT_NOTIFICATION_REQUEST\0205\022#\n\037USE" +
      "R_QUIT_NOTIFICATION_RESPONSE\0206\022$\n HOST_C" +
      "HANGE_NOTIFICATION_REQUEST\020=\022%\n!HOST_CHA" +
      "NGE_NOTIFICATION_RESPONSE\020>\022#\n\037GAME_STAR" +
      "T_NOTIFICATION_REQUEST\0207\022$\n GAME_START_N" +
      "OTIFICATION_RESPONSE\0208\022&\n\"NEW_DRAW_DATA_" +
      "NOTIFICATION_REQUEST\020G\022\'\n#NEW_DRAW_DATA_" +
      "NOTIFICATION_RESPONSE\020H\022#\n\037CLEAN_DRAW_NO",
      "TIFICATION_REQUEST\020I\022$\n CLEAN_DRAW_NOTIF" +
      "ICATION_RESPONSE\020J\022%\n!PROLONG_GAME_NOTIF" +
      "ICATION_REQUEST\020K\022&\n\"PROLONG_GAME_NOTIFI" +
      "CATION_RESPONSE\020L\022+\n\'GAME_TURN_COMPLETE_" +
      "NOTIFICATION_REQUEST\020M\022,\n(GAME_TURN_COMP" +
      "LETE_NOTIFICATION_RESPONSE\020N\022\035\n\030LOCAL_CH" +
      "ANNEL_DISCONNECT\020\311\001\022\026\n\021LOCAL_FINISH_GAME" +
      "\020\313\001\022\024\n\017LOCAL_JOIN_GAME\020\314\001\022\035\n\030LOCAL_GAME_" +
      "TURN_COMPLETE\020\315\001*\375\002\n\016GameResultCode\022\013\n\007S" +
      "UCCESS\020\000\022\023\n\017ERROR_JOIN_GAME\020\001\022\025\n\021ERROR_U",
      "SERID_NULL\020d\022 \n\034ERROR_USER_CANNOT_START_" +
      "GAME\020e\022\030\n\023ERROR_NO_SESSION_ID\020\310\001\022\037\n\032ERRO" +
      "R_NEXT_STATE_NOT_FOUND\020\311\001\022\031\n\024ERROR_SESSI" +
      "ONID_NULL\020\312\001\022 \n\033ERROR_SESSION_ALREADY_ST" +
      "ART\020\313\001\022\034\n\027ERROR_SESSION_NOT_START\020\314\001\022\037\n\032" +
      "ERROR_NO_SESSION_AVAILABLE\020\315\001\022\027\n\022ERROR_N" +
      "O_DRAW_DATA\020\255\002\022#\n\036ERROR_SYSTEM_HANDLER_N" +
      "OT_FOUND\020\216\007\022\033\n\026ERROR_SYSTEM_EXCEPTION\020\217\007" +
      "BA\n*com.orange.network.game.protocol.con" +
      "stantsB\023GameConstantsProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
