// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMessage.proto

package com.orange.network.game.protocol.message;

public final class GameMessageProtos {
  private GameMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum GameCommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    JOIN_GAME_REQUEST(0, 1),
    JOIN_GAME_RESPONSE(1, 2),
    ;
    
    public static final int JOIN_GAME_REQUEST_VALUE = 1;
    public static final int JOIN_GAME_RESPONSE_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static GameCommandType valueOf(int value) {
      switch (value) {
        case 1: return JOIN_GAME_REQUEST;
        case 2: return JOIN_GAME_RESPONSE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<GameCommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameCommandType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameCommandType>() {
            public GameCommandType findValueByNumber(int number) {
              return GameCommandType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.orange.network.game.protocol.message.GameMessageProtos.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final GameCommandType[] VALUES = {
      JOIN_GAME_REQUEST, JOIN_GAME_RESPONSE, 
    };
    
    public static GameCommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private GameCommandType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:game.GameCommandType)
  }
  
  public enum GameResultCode
      implements com.google.protobuf.ProtocolMessageEnum {
    SUCCESS(0, 0),
    ERROR_JOIN_GAME(1, 1),
    ;
    
    public static final int SUCCESS_VALUE = 0;
    public static final int ERROR_JOIN_GAME_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static GameResultCode valueOf(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return ERROR_JOIN_GAME;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<GameResultCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameResultCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameResultCode>() {
            public GameResultCode findValueByNumber(int number) {
              return GameResultCode.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.orange.network.game.protocol.message.GameMessageProtos.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final GameResultCode[] VALUES = {
      SUCCESS, ERROR_JOIN_GAME, 
    };
    
    public static GameResultCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private GameResultCode(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:game.GameResultCode)
  }
  
  public interface JoinGameRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string userId = 1;
    boolean hasUserId();
    String getUserId();
    
    // required string gameId = 2;
    boolean hasGameId();
    String getGameId();
    
    // optional int32 autoNew = 3 [default = 0];
    boolean hasAutoNew();
    int getAutoNew();
  }
  public static final class JoinGameRequest extends
      com.google.protobuf.GeneratedMessage
      implements JoinGameRequestOrBuilder {
    // Use JoinGameRequest.newBuilder() to construct.
    private JoinGameRequest(Builder builder) {
      super(builder);
    }
    private JoinGameRequest(boolean noInit) {}
    
    private static final JoinGameRequest defaultInstance;
    public static JoinGameRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public JoinGameRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.network.game.protocol.message.GameMessageProtos.internal_static_game_JoinGameRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.network.game.protocol.message.GameMessageProtos.internal_static_game_JoinGameRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string gameId = 2;
    public static final int GAMEID_FIELD_NUMBER = 2;
    private java.lang.Object gameId_;
    public boolean hasGameId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getGameId() {
      java.lang.Object ref = gameId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          gameId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGameIdBytes() {
      java.lang.Object ref = gameId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        gameId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 autoNew = 3 [default = 0];
    public static final int AUTONEW_FIELD_NUMBER = 3;
    private int autoNew_;
    public boolean hasAutoNew() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getAutoNew() {
      return autoNew_;
    }
    
    private void initFields() {
      userId_ = "";
      gameId_ = "";
      autoNew_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGameId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getGameIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, autoNew_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getGameIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, autoNew_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.network.game.protocol.message.GameMessageProtos.internal_static_game_JoinGameRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.network.game.protocol.message.GameMessageProtos.internal_static_game_JoinGameRequest_fieldAccessorTable;
      }
      
      // Construct using com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        gameId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        autoNew_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.getDescriptor();
      }
      
      public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest getDefaultInstanceForType() {
        return com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.getDefaultInstance();
      }
      
      public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest build() {
        com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest buildPartial() {
        com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest result = new com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gameId_ = gameId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.autoNew_ = autoNew_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest) {
          return mergeFrom((com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest other) {
        if (other == com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasGameId()) {
          setGameId(other.getGameId());
        }
        if (other.hasAutoNew()) {
          setAutoNew(other.getAutoNew());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasGameId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              gameId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              autoNew_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string userId = 1;
      private java.lang.Object userId_ = "";
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      void setUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
      }
      
      // required string gameId = 2;
      private java.lang.Object gameId_ = "";
      public boolean hasGameId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getGameId() {
        java.lang.Object ref = gameId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          gameId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGameId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        gameId_ = value;
        onChanged();
        return this;
      }
      public Builder clearGameId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gameId_ = getDefaultInstance().getGameId();
        onChanged();
        return this;
      }
      void setGameId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        gameId_ = value;
        onChanged();
      }
      
      // optional int32 autoNew = 3 [default = 0];
      private int autoNew_ ;
      public boolean hasAutoNew() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getAutoNew() {
        return autoNew_;
      }
      public Builder setAutoNew(int value) {
        bitField0_ |= 0x00000004;
        autoNew_ = value;
        onChanged();
        return this;
      }
      public Builder clearAutoNew() {
        bitField0_ = (bitField0_ & ~0x00000004);
        autoNew_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:game.JoinGameRequest)
    }
    
    static {
      defaultInstance = new JoinGameRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:game.JoinGameRequest)
  }
  
  public interface JoinGameResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .game.PBGameSession gameSession = 1;
    boolean hasGameSession();
    com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession getGameSession();
    com.orange.network.game.protocol.model.GameBasicProtos.PBGameSessionOrBuilder getGameSessionOrBuilder();
  }
  public static final class JoinGameResponse extends
      com.google.protobuf.GeneratedMessage
      implements JoinGameResponseOrBuilder {
    // Use JoinGameResponse.newBuilder() to construct.
    private JoinGameResponse(Builder builder) {
      super(builder);
    }
    private JoinGameResponse(boolean noInit) {}
    
    private static final JoinGameResponse defaultInstance;
    public static JoinGameResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public JoinGameResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.network.game.protocol.message.GameMessageProtos.internal_static_game_JoinGameResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.network.game.protocol.message.GameMessageProtos.internal_static_game_JoinGameResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .game.PBGameSession gameSession = 1;
    public static final int GAMESESSION_FIELD_NUMBER = 1;
    private com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession gameSession_;
    public boolean hasGameSession() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession getGameSession() {
      return gameSession_;
    }
    public com.orange.network.game.protocol.model.GameBasicProtos.PBGameSessionOrBuilder getGameSessionOrBuilder() {
      return gameSession_;
    }
    
    private void initFields() {
      gameSession_ = com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasGameSession()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getGameSession().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, gameSession_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, gameSession_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.network.game.protocol.message.GameMessageProtos.internal_static_game_JoinGameResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.network.game.protocol.message.GameMessageProtos.internal_static_game_JoinGameResponse_fieldAccessorTable;
      }
      
      // Construct using com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGameSessionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (gameSessionBuilder_ == null) {
          gameSession_ = com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.getDefaultInstance();
        } else {
          gameSessionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.getDescriptor();
      }
      
      public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse getDefaultInstanceForType() {
        return com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.getDefaultInstance();
      }
      
      public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse build() {
        com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse buildPartial() {
        com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse result = new com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (gameSessionBuilder_ == null) {
          result.gameSession_ = gameSession_;
        } else {
          result.gameSession_ = gameSessionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse) {
          return mergeFrom((com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse other) {
        if (other == com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.getDefaultInstance()) return this;
        if (other.hasGameSession()) {
          mergeGameSession(other.getGameSession());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasGameSession()) {
          
          return false;
        }
        if (!getGameSession().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.Builder subBuilder = com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.newBuilder();
              if (hasGameSession()) {
                subBuilder.mergeFrom(getGameSession());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGameSession(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .game.PBGameSession gameSession = 1;
      private com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession gameSession_ = com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession, com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.Builder, com.orange.network.game.protocol.model.GameBasicProtos.PBGameSessionOrBuilder> gameSessionBuilder_;
      public boolean hasGameSession() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession getGameSession() {
        if (gameSessionBuilder_ == null) {
          return gameSession_;
        } else {
          return gameSessionBuilder_.getMessage();
        }
      }
      public Builder setGameSession(com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession value) {
        if (gameSessionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gameSession_ = value;
          onChanged();
        } else {
          gameSessionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setGameSession(
          com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.Builder builderForValue) {
        if (gameSessionBuilder_ == null) {
          gameSession_ = builderForValue.build();
          onChanged();
        } else {
          gameSessionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeGameSession(com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession value) {
        if (gameSessionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              gameSession_ != com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.getDefaultInstance()) {
            gameSession_ =
              com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.newBuilder(gameSession_).mergeFrom(value).buildPartial();
          } else {
            gameSession_ = value;
          }
          onChanged();
        } else {
          gameSessionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearGameSession() {
        if (gameSessionBuilder_ == null) {
          gameSession_ = com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.getDefaultInstance();
          onChanged();
        } else {
          gameSessionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.Builder getGameSessionBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getGameSessionFieldBuilder().getBuilder();
      }
      public com.orange.network.game.protocol.model.GameBasicProtos.PBGameSessionOrBuilder getGameSessionOrBuilder() {
        if (gameSessionBuilder_ != null) {
          return gameSessionBuilder_.getMessageOrBuilder();
        } else {
          return gameSession_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession, com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.Builder, com.orange.network.game.protocol.model.GameBasicProtos.PBGameSessionOrBuilder> 
          getGameSessionFieldBuilder() {
        if (gameSessionBuilder_ == null) {
          gameSessionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession, com.orange.network.game.protocol.model.GameBasicProtos.PBGameSession.Builder, com.orange.network.game.protocol.model.GameBasicProtos.PBGameSessionOrBuilder>(
                  gameSession_,
                  getParentForChildren(),
                  isClean());
          gameSession_ = null;
        }
        return gameSessionBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:game.JoinGameResponse)
    }
    
    static {
      defaultInstance = new JoinGameResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:game.JoinGameResponse)
  }
  
  public interface GameMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .game.GameCommandType command = 1;
    boolean hasCommand();
    com.orange.network.game.protocol.message.GameMessageProtos.GameCommandType getCommand();
    
    // required int32 messageId = 2;
    boolean hasMessageId();
    int getMessageId();
    
    // optional .game.GameResultCode resultCode = 3;
    boolean hasResultCode();
    com.orange.network.game.protocol.message.GameMessageProtos.GameResultCode getResultCode();
    
    // optional .game.JoinGameRequest joinGameRequest = 11;
    boolean hasJoinGameRequest();
    com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest getJoinGameRequest();
    com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequestOrBuilder getJoinGameRequestOrBuilder();
    
    // optional .game.JoinGameResponse joinGameResponse = 12;
    boolean hasJoinGameResponse();
    com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse getJoinGameResponse();
    com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponseOrBuilder getJoinGameResponseOrBuilder();
  }
  public static final class GameMessage extends
      com.google.protobuf.GeneratedMessage
      implements GameMessageOrBuilder {
    // Use GameMessage.newBuilder() to construct.
    private GameMessage(Builder builder) {
      super(builder);
    }
    private GameMessage(boolean noInit) {}
    
    private static final GameMessage defaultInstance;
    public static GameMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.network.game.protocol.message.GameMessageProtos.internal_static_game_GameMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.network.game.protocol.message.GameMessageProtos.internal_static_game_GameMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .game.GameCommandType command = 1;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private com.orange.network.game.protocol.message.GameMessageProtos.GameCommandType command_;
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.orange.network.game.protocol.message.GameMessageProtos.GameCommandType getCommand() {
      return command_;
    }
    
    // required int32 messageId = 2;
    public static final int MESSAGEID_FIELD_NUMBER = 2;
    private int messageId_;
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getMessageId() {
      return messageId_;
    }
    
    // optional .game.GameResultCode resultCode = 3;
    public static final int RESULTCODE_FIELD_NUMBER = 3;
    private com.orange.network.game.protocol.message.GameMessageProtos.GameResultCode resultCode_;
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.orange.network.game.protocol.message.GameMessageProtos.GameResultCode getResultCode() {
      return resultCode_;
    }
    
    // optional .game.JoinGameRequest joinGameRequest = 11;
    public static final int JOINGAMEREQUEST_FIELD_NUMBER = 11;
    private com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest joinGameRequest_;
    public boolean hasJoinGameRequest() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest getJoinGameRequest() {
      return joinGameRequest_;
    }
    public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequestOrBuilder getJoinGameRequestOrBuilder() {
      return joinGameRequest_;
    }
    
    // optional .game.JoinGameResponse joinGameResponse = 12;
    public static final int JOINGAMERESPONSE_FIELD_NUMBER = 12;
    private com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse joinGameResponse_;
    public boolean hasJoinGameResponse() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse getJoinGameResponse() {
      return joinGameResponse_;
    }
    public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponseOrBuilder getJoinGameResponseOrBuilder() {
      return joinGameResponse_;
    }
    
    private void initFields() {
      command_ = com.orange.network.game.protocol.message.GameMessageProtos.GameCommandType.JOIN_GAME_REQUEST;
      messageId_ = 0;
      resultCode_ = com.orange.network.game.protocol.message.GameMessageProtos.GameResultCode.SUCCESS;
      joinGameRequest_ = com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.getDefaultInstance();
      joinGameResponse_ = com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasJoinGameRequest()) {
        if (!getJoinGameRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasJoinGameResponse()) {
        if (!getJoinGameResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, command_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, messageId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(11, joinGameRequest_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(12, joinGameResponse_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, command_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, messageId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, joinGameRequest_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, joinGameResponse_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.orange.network.game.protocol.message.GameMessageProtos.GameMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.GameMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.GameMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.GameMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.GameMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.GameMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.GameMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.GameMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.GameMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.message.GameMessageProtos.GameMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.network.game.protocol.message.GameMessageProtos.GameMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.orange.network.game.protocol.message.GameMessageProtos.GameMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.network.game.protocol.message.GameMessageProtos.internal_static_game_GameMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.network.game.protocol.message.GameMessageProtos.internal_static_game_GameMessage_fieldAccessorTable;
      }
      
      // Construct using com.orange.network.game.protocol.message.GameMessageProtos.GameMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getJoinGameRequestFieldBuilder();
          getJoinGameResponseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        command_ = com.orange.network.game.protocol.message.GameMessageProtos.GameCommandType.JOIN_GAME_REQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        resultCode_ = com.orange.network.game.protocol.message.GameMessageProtos.GameResultCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (joinGameRequestBuilder_ == null) {
          joinGameRequest_ = com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.getDefaultInstance();
        } else {
          joinGameRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (joinGameResponseBuilder_ == null) {
          joinGameResponse_ = com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.getDefaultInstance();
        } else {
          joinGameResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.network.game.protocol.message.GameMessageProtos.GameMessage.getDescriptor();
      }
      
      public com.orange.network.game.protocol.message.GameMessageProtos.GameMessage getDefaultInstanceForType() {
        return com.orange.network.game.protocol.message.GameMessageProtos.GameMessage.getDefaultInstance();
      }
      
      public com.orange.network.game.protocol.message.GameMessageProtos.GameMessage build() {
        com.orange.network.game.protocol.message.GameMessageProtos.GameMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.orange.network.game.protocol.message.GameMessageProtos.GameMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.orange.network.game.protocol.message.GameMessageProtos.GameMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.orange.network.game.protocol.message.GameMessageProtos.GameMessage buildPartial() {
        com.orange.network.game.protocol.message.GameMessageProtos.GameMessage result = new com.orange.network.game.protocol.message.GameMessageProtos.GameMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (joinGameRequestBuilder_ == null) {
          result.joinGameRequest_ = joinGameRequest_;
        } else {
          result.joinGameRequest_ = joinGameRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (joinGameResponseBuilder_ == null) {
          result.joinGameResponse_ = joinGameResponse_;
        } else {
          result.joinGameResponse_ = joinGameResponseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.network.game.protocol.message.GameMessageProtos.GameMessage) {
          return mergeFrom((com.orange.network.game.protocol.message.GameMessageProtos.GameMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orange.network.game.protocol.message.GameMessageProtos.GameMessage other) {
        if (other == com.orange.network.game.protocol.message.GameMessageProtos.GameMessage.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasMessageId()) {
          setMessageId(other.getMessageId());
        }
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (other.hasJoinGameRequest()) {
          mergeJoinGameRequest(other.getJoinGameRequest());
        }
        if (other.hasJoinGameResponse()) {
          mergeJoinGameResponse(other.getJoinGameResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCommand()) {
          
          return false;
        }
        if (!hasMessageId()) {
          
          return false;
        }
        if (hasJoinGameRequest()) {
          if (!getJoinGameRequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasJoinGameResponse()) {
          if (!getJoinGameResponse().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.orange.network.game.protocol.message.GameMessageProtos.GameCommandType value = com.orange.network.game.protocol.message.GameMessageProtos.GameCommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                command_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              messageId_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.orange.network.game.protocol.message.GameMessageProtos.GameResultCode value = com.orange.network.game.protocol.message.GameMessageProtos.GameResultCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                resultCode_ = value;
              }
              break;
            }
            case 90: {
              com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.Builder subBuilder = com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.newBuilder();
              if (hasJoinGameRequest()) {
                subBuilder.mergeFrom(getJoinGameRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setJoinGameRequest(subBuilder.buildPartial());
              break;
            }
            case 98: {
              com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.Builder subBuilder = com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.newBuilder();
              if (hasJoinGameResponse()) {
                subBuilder.mergeFrom(getJoinGameResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setJoinGameResponse(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .game.GameCommandType command = 1;
      private com.orange.network.game.protocol.message.GameMessageProtos.GameCommandType command_ = com.orange.network.game.protocol.message.GameMessageProtos.GameCommandType.JOIN_GAME_REQUEST;
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.orange.network.game.protocol.message.GameMessageProtos.GameCommandType getCommand() {
        return command_;
      }
      public Builder setCommand(com.orange.network.game.protocol.message.GameMessageProtos.GameCommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = com.orange.network.game.protocol.message.GameMessageProtos.GameCommandType.JOIN_GAME_REQUEST;
        onChanged();
        return this;
      }
      
      // required int32 messageId = 2;
      private int messageId_ ;
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getMessageId() {
        return messageId_;
      }
      public Builder setMessageId(int value) {
        bitField0_ |= 0x00000002;
        messageId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageId_ = 0;
        onChanged();
        return this;
      }
      
      // optional .game.GameResultCode resultCode = 3;
      private com.orange.network.game.protocol.message.GameMessageProtos.GameResultCode resultCode_ = com.orange.network.game.protocol.message.GameMessageProtos.GameResultCode.SUCCESS;
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.orange.network.game.protocol.message.GameMessageProtos.GameResultCode getResultCode() {
        return resultCode_;
      }
      public Builder setResultCode(com.orange.network.game.protocol.message.GameMessageProtos.GameResultCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        resultCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        resultCode_ = com.orange.network.game.protocol.message.GameMessageProtos.GameResultCode.SUCCESS;
        onChanged();
        return this;
      }
      
      // optional .game.JoinGameRequest joinGameRequest = 11;
      private com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest joinGameRequest_ = com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest, com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.Builder, com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequestOrBuilder> joinGameRequestBuilder_;
      public boolean hasJoinGameRequest() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest getJoinGameRequest() {
        if (joinGameRequestBuilder_ == null) {
          return joinGameRequest_;
        } else {
          return joinGameRequestBuilder_.getMessage();
        }
      }
      public Builder setJoinGameRequest(com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest value) {
        if (joinGameRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          joinGameRequest_ = value;
          onChanged();
        } else {
          joinGameRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setJoinGameRequest(
          com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.Builder builderForValue) {
        if (joinGameRequestBuilder_ == null) {
          joinGameRequest_ = builderForValue.build();
          onChanged();
        } else {
          joinGameRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeJoinGameRequest(com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest value) {
        if (joinGameRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              joinGameRequest_ != com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.getDefaultInstance()) {
            joinGameRequest_ =
              com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.newBuilder(joinGameRequest_).mergeFrom(value).buildPartial();
          } else {
            joinGameRequest_ = value;
          }
          onChanged();
        } else {
          joinGameRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearJoinGameRequest() {
        if (joinGameRequestBuilder_ == null) {
          joinGameRequest_ = com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.getDefaultInstance();
          onChanged();
        } else {
          joinGameRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.Builder getJoinGameRequestBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getJoinGameRequestFieldBuilder().getBuilder();
      }
      public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequestOrBuilder getJoinGameRequestOrBuilder() {
        if (joinGameRequestBuilder_ != null) {
          return joinGameRequestBuilder_.getMessageOrBuilder();
        } else {
          return joinGameRequest_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest, com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.Builder, com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequestOrBuilder> 
          getJoinGameRequestFieldBuilder() {
        if (joinGameRequestBuilder_ == null) {
          joinGameRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest, com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.Builder, com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequestOrBuilder>(
                  joinGameRequest_,
                  getParentForChildren(),
                  isClean());
          joinGameRequest_ = null;
        }
        return joinGameRequestBuilder_;
      }
      
      // optional .game.JoinGameResponse joinGameResponse = 12;
      private com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse joinGameResponse_ = com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse, com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.Builder, com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponseOrBuilder> joinGameResponseBuilder_;
      public boolean hasJoinGameResponse() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse getJoinGameResponse() {
        if (joinGameResponseBuilder_ == null) {
          return joinGameResponse_;
        } else {
          return joinGameResponseBuilder_.getMessage();
        }
      }
      public Builder setJoinGameResponse(com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse value) {
        if (joinGameResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          joinGameResponse_ = value;
          onChanged();
        } else {
          joinGameResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setJoinGameResponse(
          com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.Builder builderForValue) {
        if (joinGameResponseBuilder_ == null) {
          joinGameResponse_ = builderForValue.build();
          onChanged();
        } else {
          joinGameResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeJoinGameResponse(com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse value) {
        if (joinGameResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              joinGameResponse_ != com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.getDefaultInstance()) {
            joinGameResponse_ =
              com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.newBuilder(joinGameResponse_).mergeFrom(value).buildPartial();
          } else {
            joinGameResponse_ = value;
          }
          onChanged();
        } else {
          joinGameResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearJoinGameResponse() {
        if (joinGameResponseBuilder_ == null) {
          joinGameResponse_ = com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.getDefaultInstance();
          onChanged();
        } else {
          joinGameResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.Builder getJoinGameResponseBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getJoinGameResponseFieldBuilder().getBuilder();
      }
      public com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponseOrBuilder getJoinGameResponseOrBuilder() {
        if (joinGameResponseBuilder_ != null) {
          return joinGameResponseBuilder_.getMessageOrBuilder();
        } else {
          return joinGameResponse_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse, com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.Builder, com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponseOrBuilder> 
          getJoinGameResponseFieldBuilder() {
        if (joinGameResponseBuilder_ == null) {
          joinGameResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse, com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.Builder, com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponseOrBuilder>(
                  joinGameResponse_,
                  getParentForChildren(),
                  isClean());
          joinGameResponse_ = null;
        }
        return joinGameResponseBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:game.GameMessage)
    }
    
    static {
      defaultInstance = new GameMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:game.GameMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_JoinGameRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_JoinGameRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_JoinGameResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_JoinGameResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_GameMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_GameMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021GameMessage.proto\022\004game\032\017GameBasic.pro" +
      "to\"E\n\017JoinGameRequest\022\016\n\006userId\030\001 \002(\t\022\016\n" +
      "\006gameId\030\002 \002(\t\022\022\n\007autoNew\030\003 \001(\005:\0010\"<\n\020Joi" +
      "nGameResponse\022(\n\013gameSession\030\001 \002(\0132\023.gam" +
      "e.PBGameSession\"\324\001\n\013GameMessage\022&\n\007comma" +
      "nd\030\001 \002(\0162\025.game.GameCommandType\022\021\n\tmessa" +
      "geId\030\002 \002(\005\022(\n\nresultCode\030\003 \001(\0162\024.game.Ga" +
      "meResultCode\022.\n\017joinGameRequest\030\013 \001(\0132\025." +
      "game.JoinGameRequest\0220\n\020joinGameResponse" +
      "\030\014 \001(\0132\026.game.JoinGameResponse*@\n\017GameCo",
      "mmandType\022\025\n\021JOIN_GAME_REQUEST\020\001\022\026\n\022JOIN" +
      "_GAME_RESPONSE\020\002*2\n\016GameResultCode\022\013\n\007SU" +
      "CCESS\020\000\022\023\n\017ERROR_JOIN_GAME\020\001B=\n(com.oran" +
      "ge.network.game.protocol.messageB\021GameMe" +
      "ssageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_game_JoinGameRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_game_JoinGameRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_JoinGameRequest_descriptor,
              new java.lang.String[] { "UserId", "GameId", "AutoNew", },
              com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.class,
              com.orange.network.game.protocol.message.GameMessageProtos.JoinGameRequest.Builder.class);
          internal_static_game_JoinGameResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_game_JoinGameResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_JoinGameResponse_descriptor,
              new java.lang.String[] { "GameSession", },
              com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.class,
              com.orange.network.game.protocol.message.GameMessageProtos.JoinGameResponse.Builder.class);
          internal_static_game_GameMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_game_GameMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_GameMessage_descriptor,
              new java.lang.String[] { "Command", "MessageId", "ResultCode", "JoinGameRequest", "JoinGameResponse", },
              com.orange.network.game.protocol.message.GameMessageProtos.GameMessage.class,
              com.orange.network.game.protocol.message.GameMessageProtos.GameMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.orange.network.game.protocol.model.GameBasicProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
